title: Majapahit & Australia, and a Game-Theoretic Simulation.
description: This is the official GitHub Pages website for my project, entitled:
> An Investigation into the Majapahit Geopolitical Model - Parallels between the Majapahit Empire and the Modern Australian State, with a Large-Scale Game-Theoretic Agentic Simulation of a Proposed Systemic Model Of Australia in the Next 50 Years
theme: jekyll-theme-minimal 
logo: Hall-Alister Logo GitHub Pages.png
